---
kind: pipeline
type: docker
name: review

platform:
  os: linux
  arch: amd64

steps:
- name: fmt
  image: golang:1.17
  commands:
  - ./check_gofmt
  volumes:
  - name: deps
    path: /go/pkg

- name: easyjson
  image: polygonio/tool-serialization:latest
  commands:
  - ./check_easyjson
  volumes:
  - name: deps
    path: /go/pkg

- name: lint
  pull: always
  image: polygonio/go-linter:v1.13
  environment:
    IS_LIB: 1
  volumes:
  - name: deps
    path: /go/pkg

- name: test
  image: golang:1.17
  commands:
  - go test -v ./...
  volumes:
  - name: deps
    path: /go/pkg

volumes:
- name: deps
  temp: {}

trigger:
  branch:
  - master
  event:
  - pull_request

...
