name: Review

on:
  pull_request:
    branches:
      - 'master'

defaults:
  run:
    working-directory: .

jobs:
  lint:
    runs-on: ubuntu-latest
    name: golangci-lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.0
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: test
        run: go test ./...
        env:
          GIN_MODE: debug
